name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    # strategy.matrix.node-version: 16.x
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Build and Deploy
      uses: jenkey2011/vuepress-deploy@1.0.1
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BUILD_SCRIPT: yarn && yarn build
        TARGET_BRANCH: gh-pages
        BUILD_DIR: build/